#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x14,0xd5,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x14,0x0d,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
